//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.central.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gas_stations
    {
        public int station_id { get; set; }
        public string address { get; set; }
        public double price_AI92 { get; set; }
        public double price_AI95 { get; set; }
        public double price_AI98 { get; set; }
        public double price_diesel { get; set; }
        public int remainder_AI92 { get; set; }
        public int remainder_AI95 { get; set; }
        public int remainder_AI98 { get; set; }
        public int remainder_diesel { get; set; }
    }
}
